### ISSUE TITLE
The Streamlit demo uses the `master` branch

### ISSUE THREAD

**Issue by bdura** [aphp/edspdf#13]
## Description

The demo is currently down, with the following error message:

```
File "/home/appuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/app/edspdf/demo/app.py", line 5, in <module>
    from thinc.config import Config
```

I think it might be linked to the `master` branch, and not the new default `dev` branch.

**Comment by percevalw** [comment]
Ah, thanks for the info! I'll be merging dev with master soon, but in the meantime, hardcoding `@master` into streamlit requirements seems to do the trick.
