### ISSUE TITLE
Pydantic dependency too old

### ISSUE THREAD

**Issue by xav-hydra** [aphp/edspdf#29]
This project uses `pydantic<2` and it would be nice to have this fixed.

## Description

This project uses `pydantic<2` and it would be nice to have this fixed as I use it in a jupyterhub which uses `pydantic>=2`. Also to note that even `edsnlp`, which i'm also using, accepts version 2+.

## How to reproduce the bug
```
pip install jupyterhub==5.1.0 "edsnlp[ml]>=0.13" edspdf==0.9.1
```
## Your Environment

- Operating System: [ubuntu](https://github.com/jupyter/docker-stacks/blob/main/images/all-spark-notebook/Dockerfile) and [alpine](https://github.com/bitnami/containers/blob/main/bitnami/spark/3.5/debian-12/Dockerfile) based docker images (modified)
- Python Version Used: 3.11.9
- EDS-PDF Version Used: 0.9.1
- Environment Information: Kubernetes on premise

**Comment by percevalw** [comment]
Indeed! Our main pydantic v2.0 blocker was [confit](https://github.com/aphp/confit), which we adapted a few months ago, so it shouldn't be too difficult. I'll keep you posted.
